apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
{{- include "hpe-ezua.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
{{- include "hpe-ezua.labels" . | nindent 8 }}
    spec:
      containers:
      - name: triageai
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 7860
        volumeMounts:
        - name: config-data
          mountPath: /app/data
        resources:
{{- toYaml .Values.resources | nindent 10 }}
      securityContext:
        fsGroup: 1000
      volumes:
      - name: config-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data